---
- name: Ensure a 'felix' user on the remote host.
  hosts: all
  remote_user: root

  vars_files:
    - vars/main.yml

  tasks:
    - name: Install base development tools
      pacman: name=base-devel state=present

    - name: Install the user felix
      user: name=felix
            comment="{{full_name}}"
            groups=wheel,network,uucp,storage,users,audio,optical,power

    - name: Move public ssh keys to the authorized keys
      authorized_key: user=felix key="{{item}}"
      with_file:
        - files/noctua-nivalis.pub

- name: Set-up an Arch-Linux desktop with XMonad and generally useful programs.
  hosts: all
  remote_user: felix

  vars_files:
    - vars/main.yml

  roles:
    - zsh
    - vim
