---
- name: Ensure a 'felix' user on the remote host.
  hosts: all
  remote_user: root

  vars_files:
    - vars/main.yml

  vars_prompt:
    - name: "user_password"
      prompt: password for user
      private: yes
      encrypt: "md5_crypt"
      confirm: yes
      salt_size: 7

  tasks:
    - name: Install base development tools
      pacman: name=base-devel state=present

    - name: Install Python 3
      pacman: name=python state=present

    - name: Install the user
      user: name={{username}}
            comment="{{full_name}}"
            password="{{user_password}}"
            groups=wheel,network,uucp,storage,users,audio,optical,power

    - name: Allow wheelers to use sudo
      copy: src=files/sudoers dest=/etc/sudoers

    - name: Move public ssh keys to the authorized keys
      authorized_key: user={{username}} key="{{item}}"
      with_file:
        - files/noctua-nivalis.pub

- name: Set-up an Arch-Linux desktop with XMonad and generally useful programs.
  hosts: all
  remote_user: felix

  vars_files:
    - vars/main.yml

  roles:
    - zsh
  #  - vim
  #  - ntp
  #  - xmonad
    - programs

