---
- name: Set-up an Arch-Linux desktop with XMonad and generally useful programs.
  hosts: all
  remote_user: felix

  vars_files:
    - vars/main.yml

  roles:
    - zsh
    - vim
    - ntp
    - xmonad
    - programs

