---
- name: Check if packer is already installed
  command: pacman -Qi packer
  register: packer_installed
  ignore_errors: True

- name: Download the packer build files
  when: packer_installed|failed
  git: repo=https://aur.archlinux.org/packer.git dest=/tmp/packer

- name: Determine packer dependencies
  shell: sed '/^depends=/!d;/)/q' /tmp/packer/PKGBUILD | sed "s/[^']*'//;s/' '/\n/g;s/'.*//"
  register: dependencies

- name: Install packer dependencies
  pacman: name={{item}} state=present
  with_items: "{{dependencies.stdout_lines}}"
  remote_user: root

- name: Make the packer package
  when: packer_installed|failed
  command: makepkg -f
  args:
    chdir: /tmp/packer

- name: Install the packer package
  when: packer_installed|failed
  shell: pacman --noconfirm -U packer*.pkg.tar.xz
  remote_user: root
  args:
    chdir: /tmp/packer

