---
- command: pacman -Qi {{ package }}
  register: installed
  ignore_errors: True

- when: installed|failed
  git: repo={{ url | default("https://aur.archlinux.org/" + package + ".git") }} dest=/tmp/{{ package }}

- when: installed|failed
  shell: 'source /tmp/{{ package }}/PKGBUILD; for d in ${makedepends[@]}; do echo $d; done'
  register: makedepends

- when: installed|failed
  pacman: name={{ item }} state=present
  become: yes
  with_items: "{{ makedepends.stdout_lines | default([]) }}"

- when: installed|failed
  command: makepkg -f --nodeps
  args:
    chdir: /tmp/{{ package }}

- when: installed|failed
  shell: pacman --noconfirm -U {{ package }}*.pkg.tar.xz
  become: yes
  args:
    chdir: /tmp/{{ package }}

- when: installed|failed
  file: path=/tmp/{{ package }} state=absent

