---
- command: pacman -Qi {{ package }}
  register: installed
  ignore_errors: True

- when: installed|failed and makedepends is defined
  pacman: name={{ item }} state=present
  with_items: "{{ makedepends }}"

- when: installed|failed
  git: repo={{ url }} dest=/tmp/{{ package }}

- when: installed|failed
  command: makepkg -f --nodeps
  args:
    chdir: /tmp/{{ package }}

- when: installed|failed
  shell: pacman --noconfirm -U {{ package }}*.pkg.tar.xz
  remote_user: root
  args:
    chdir: /tmp/{{ package }}

- when: installed|failed
  file: path=/tmp/{{ package }} state=absent

