---
- name: Install VIM package
  pacman: name=vim state=present
  become: yes

- name: Make directories for swap files
  file: path=~/.vim/tmp/swap/ state=directory mode=0755

- name: Make directory for backup files.
  file: path=~/.vim/tmp/backup/ state=directory mode=0755

- name: Add the vimrc
  copy: src=vimrc dest=~/.vim/vimrc

- name: Install Vundle
  git: repo=https://github.com/VundleVim/Vundle.vim.git
       dest=~/.vim/bundle/Vundle.vim

- name: Install stuff using Vundle
  command: vim +PluginInstall +qall

- pacman: name=clang state=present
  become: yes

- pacman: name=cmake state=present
  become: yes

- file: path=~/ycm_build state=directory mode=0755

- command: cmake -G "Unix Makefiles" -DUSE_SYSTEM_LIBCLANG=ON . ~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp
  args:
    chdir: ~/ycm_build

- command: make ycm_support_libs
  args:
    chdir: ~/ycm_build

